package com.example.scanencyclopedia;

public class ModelClasses {
    public static final String[] MODEL_CLASSES = new String[]{
            "AFRICAN CROWNED CRANE",
            "RED CANARY: The domestic canary, often simply known as the canary, is a domesticated form of the wild canary, a small songbird in the finch family originating from the Macaronesian Islands. Canaries were first bred in captivity in the 17th century, having been brought to Europe by Spanish sailors.",
            "ALBATROSS", "ALEXANDRINE PARAKEET", "AMERICAN AVOCET", "AMERICAN BITTERN", "AMERICAN COOT", "AMERICAN GOLDFINCH",
            "AMERICAN KESTREL", "OSTRICH: Struthio is a genus of birds in the order Struthioniformes, whose members are the ostriches. It is part of the infra-class Palaeognathae, a diverse group of flightless birds also known as ratites that includes the emus, rheas, and kiwis.",
            "HOUSE SPARROW:The house sparrow is a bird of the sparrow family Passeridae, found in most parts of the world. It is a small bird that has a typical length of 16 cm and a mass of 24–39.5 g. Females and young birds are coloured palbrown and grey, and males have brighter black, white, and brown markings.",
            "WHITE-THROATED KINGBIRD:The white-throated kingbird (Tyrannus albogularis) is a species of bird in the family Tyrannidae, the tyrant flycatchers. It is found in Bolivia, Brazil, Colombia, Ecuador, Peru, and Venezuela, and in the Guianas of Guyana, Suriname and French Guiana. Its natural habitats are subtropical or tropical moist lowland forests and subtropical or tropical moist shrubland.",
            "ANNAS HUMMINGBIRD", "ANTBIRD", "ARARIPE MANAKIN",
            "ROBIN: The American robin is a migratory songbird of the true thrush genus and Turdidae, the wider thrush family. It is named after the European robin because of its reddish-orange breast, though the two species are not closely related, with the European robin belonging to the Old World flycatcher family.",
            "MYNA: The myna is a bird of the starling family. This is a group of passerine birds which are native to southern Asia, especially India, Pakistan and Bangladesh.",
            "BALD IBIS", "CROW: crow, (genus Corvus), any of various glossy black birds found in most parts of the world, with the exception of southern South America. Crows are generally smaller and not as thick-billed as ravens, which belong to the same genus. A large majority of the 40 or so Corvus species are known as crows, and the name has been applied to other, unrelated birds. Large crows measure about 0.5 metre (20 inches) long, with wingspans that can reach 1 metre (39 inches).",
            "BALTIMORE ORIOLE", "BANANAQUIT", "BANDED BROADBILL",
            "BALD EAGLE: The bald eagle is a bird of prey found in North America. A sea eagle, it has two known subspecies and forms a species pair with the white-tailed eagle. Its range includes most of Canada and Alaska, all of the contiguous United States, and northern Mexico.",
            "BLACK VULTURE: The black vulture, also known as the American black vulture, is a bird in the New World vulture family whose range extends from the northeastern United States to Peru, Central Chile and Uruguay in South America",
            "BARN OWL: The barn owl is the most widely distributed species of owl in the world and one of the most widespread of all species of birds, being found almost everywhere in the world except for the polar and desert regions, Asia north of the Himalayas, most of Indonesia, and some Pacific Islands.",
            "BARN SWALLOW", "BARRED PUFFBIRD", "BAY-BREASTED WARBLER", "BEARDED BARBET", "BEARDED BELLBIRD", "BEARDED REEDLING", "BELTED KINGFISHER", "BIRD OF PARADISE", "BLACK & YELLOW bROADBILL", "BLACK BAZA", "BLACK FRANCOLIN", "BLACK SKIMMER", "BLACK SWAN", "BLACK TAIL CRAKE", "BLACK THROATED BUSHTIT", "BLACK THROATED WARBLER", "BLACK VULTURE", "BLACK-CAPPED CHICKADEE", "BLACK-NECKED GREBE", "BLACK-THROATED SPARROW", "BLACKBURNIAM WARBLER", "BLONDE CRESTED WOODPECKER", "BLUE COAU", "BLUE GROUSE", "BLUE HERON", "BLUE THROATED TOUCANET", "BOBOLINK", "BORNEAN BRISTLEHEAD", "BORNEAN LEAFBIRD", "BORNEAN PHEASANT", "BROWN CREPPER", "BROWN NOODY", "BROWN THRASHER", "BULWERS PHEASANT", "CACTUS WREN", "CALIFORNIA CONDOR", "CALIFORNIA GULL", "CALIFORNIA QUAIL", "CANARY", "CAPE MAY WARBLER",
            "CAPPED HERON", "CAPUCHINBIRD", "CARMINE BEE-EATER", "CASPIAN TERN", "CASSOWARY", "CEDAR WAXWING", "CERULEAN WARBLER", "CHARA DE COLLAR", "CHIPPING SPARROW", "CHUKAR PARTRIDGE", "CINNAMON TEAL", "CLARKS NUTCRACKER", "COCK OF THE  ROCK", "COCKATOO", "COLLARED ARACARI",
            "ROCK DOVE: The rock dove, rock pigeon, or common pigeon is a member of the bird family Columbidae. In common usage, it is often simply referred to as the 'pigeon'. The domestic pigeon descended from this species. Escaped domestic pigeons have increased the populations of feral pigeons around the world.",
            "COMMON FIRECREST", "COMMON GRACKLE", "COMMON HOUSE MARTIN",
            "PEACOCOK: Peafowl is a common name for three bird species in the genera Pavo and Afropavo within the tribe Pavonini of the family Phasianidae, the pheasants and their allies. Male peafowl are referred to as peacocks, and female peafowl are referred to as peahens, even though peafowl of either sex are often referred to colloquially as 'peacocks'.", "CRESTEDCARACARA", "RED HEADED WOODPECKER: The red-headed woodpecker is a mid-sized woodpecker found in temperate North America. Its breeding habitat is open country across southern Canada and the Eastern-central United States.",
            "COMMON POORWILL", "COMMON STARLING", "COUCHS KINGBIRD",
            "ALEXANDRINE PARAKEET: The Alexandrine parakeet (Psittacula eupatria), also known as the Alexandrine parrot, is a medium-sized parrot in the genus Psittacula of the family Psittaculidae. It is named after Alexander the Great, who transported numerous birds from Punjab to various European and Mediterranean countries and regions, where they were prized by the royalty, nobility and warlords. The Alexandrine parakeet has established feral populations in Iraq, Kuwait Saudi Arabia, Bahrain, Qatar, the United Arab Emirates, Iran where it lives alongside feral populations of its close relative, the rose-ringed parakeet (Psittacula krameri).", "CUBAN TROGON", "CRIMSON SUNBIRD: The crimson sunbird is a species of bird in the sunbird family which feed largely on nectar, although they will also take insects, especially when feeding the young. Flight is fast and direct on their short wings. Most species can take nectar by hovering like a hummingbird, but usually perch to feed.",
            "CROWNED PIGEON", "CRIMSON SUNBIRD", "D-ARNAUDS BARBET", "DOWNY WOODPECKER",
            "DARK EYED JUNCO", "DOUBLE BARRED FINCH", "DOUBLE BRESTED CORMARANT",
            "BLACK SWAN: The black swan is a large waterbird, a species of swan which breeds mainly in the southeast and southwest regions of Australia. Within Australia, the black swan is nomadic, with erratic migration patterns dependent upon climatic conditions. It is a large bird with mostly black plumage and a red bill.",
            "EASTERN BLUEBIRD",
            "KIWI: Kiwi are flightless birds endemic to New Zealand of the genus Apteryx and family Apterygidae. Approximately the size of a domestic chicken, kiwi are by far the smallest living ratites.",
            "EASTERN MEADOWLARK",
            "EASTERN TOWEE",
            "ELLIOTS  PHEASANT", "EMPEROR PENGUIN",
            "EMU", "ENGGANO MYNA", "EURASIAN GOLDEN ORIOLE", "EURASIAN MAGPIE", "EVENING GROSBEAK", "FAIRY BLUEBIRD",
            "FIRE TAILLED MYZORNIS", "FLAME TANAGER", "FLAMINGO", "FRIGATE", "GAMBELS QUAIL", "GANG GANG COCKATOO",
            "GILA WOODPECKER", "GILDED FLICKER", "GLOSSY IBIS", "GO AWAY BIRD", "GOLD WING WARBLER", "GOLDEN CHEEKED WARBLER",
            "GOLDEN CHLOROPHONIA", "GOLDEN EAGLE", "GOLDEN PHEASANT", "GOLDEN PIPIT", "GOULDIAN FINCH", "GRAY CATBIRD",
            "GRAY PARTRIDGE", "GREAT KISKADEE",
            "FLAMINGO: Flamingos or flamingoes are a type of wading bird in the family Phoenicopteridae, which is the only bird family in the order Phoenicopteriformes. There are four flamingo species distributed throughout the Americas (including the Caribbean), and two species native to Africa, Asia, and Europe.",
            "GREATOR SAGE GROUSE", "GREEN BROADBILL", "GREEN JAY",
            "SANHILL CRANE: The sandhill crane is a species of large crane of North America and extreme northeastern Siberia. The common name of this bird refers to habitat like that at the Platte River, on the edge of Nebraska's Sandhills on the American Great Plains.",
            "GREY PLOVER", "GUINEA TURACO", "GUINEAFOWL", "GYRFALCON", "HARLEQUIN DUCK", "HARPY EAGLE", "HAWAIIAN GOOSE",
            "EMPEROR PENGUIN: The emperor penguin is the tallest and heaviest of all living penguin species and is endemic to Antarctica. The male and female are similar in plumage and size, reaching 100 cm in length and weighing from 22 to 45 kg.",
            "HELMET VANGA", "HIMALAYAN MONAL", "HOATZIN", "HOODED MERGANSER",
            "ALBATROSS: Albatrosses, of the biological family Diomedeidae, are large seabirds related to the procellariids, storm petrels, and diving petrels in the order Procellariiformes. They range widely in the Southern Ocean and the North Pacific",
            "HORNED GUAN", "HORNED LARK", "HORNED SUNGEM", "HOUSE FINCH", "HOUSE SPARROW", "HYACINTH MACAW", "IMPERIAL SHAQ",
            "INCA TERN", "INDIAN BUSTARD", "INDIAN PITTA", "INDIAN ROLLER", "INDIGO BUNTING", "IWI", "JABIRU", "JAVA SPARROW",
            "KAGU", "KAKAPO", "KILLDEAR", "KING VULTURE", "KOOKABURRA",
            "LARK BUNTING", "LILAC ROLLER", "LONG-EARED OWL",
            "MAGPIE GOOSE", "MALABAR HORNBILL", "MALACHITE KINGFISHER", "MALAGASY WHITE EYE",
            "MALEO", "MALLARD DUCK",
            "MANDRIN DUCK", "MARABOU STORK", "MASKED BOOBY", "MASKED LAPWING", "MIKADO  PHEASANT", "MOURNING DOVE", "MYNA",
            "NICOBAR PIGEON", "NOISY FRIARBIRD", "NORTHERN BALD IBIS", "NORTHERN CARDINAL", "NORTHERN FLICKER", "NORTHERN GANNET",
            "NORTHERN GOSHAWK", "NORTHERN JACANA", "NORTHERN MOCKINGBIRD", "NORTHERN PARULA", "NORTHERN RED BISHOP",
            "NORTHERN SHOVELER", "OCELLATED TURKEY", "OKINAWA RAIL", "ORANGE BRESTED BUNTING", "OSPREY", "OSTRICH",
            "OVENBIRD", "OYSTER CATCHER", "PAINTED BUNTIG", "PALILA", "PARADISE TANAGER", "PARAKETT  AKULET", "PARUS MAJOR",
            "PEACOCK", "PELICAN", "PEREGRINE FALCON", "PHILIPPINE EAGLE", "PINK ROBIN", "PUFFIN", "PURPLE FINCH",
            "PURPLE GALLINULE", "PURPLE MARTIN", "PURPLE SWAMPHEN", "PYGMY KINGFISHER", "QUETZAL", "RAINBOW LORIKEET",
            "RAZORBILL", "RED BEARDED BEE EATER", "RED BELLIED PITTA", "RED BROWED FINCH", "RED FACED CORMORANT",
            "RED FACED WARBLER", "RED FODY", "RED HEADED DUCK",
            "RED HEADED WOODPECKER", "RED HONEY CREEPER", "RED NAPED TROGON", "RED TAILED HAWK", "RED TAILED THRUSH",
            "RED WINGED BLACKBIRD", "RED WISKERED BULBUL", "REGENT BOWERBIRD", "RING-NECKED PHEASANT", "ROADRUNNER",
            "ROBIN", "ROCK DOVE", "ROSY FACED LOVEBIRD", "ROUGH LEG BUZZARD", "ROYAL FLYCATCHER", "RUBY THROATED HUMMINGBIRD",
            "RUDY KINGFISHER", "RUFOUS KINGFISHER", "RUFUOS MOTMOT", "SAMATRAN THRUSH", "SAND MARTIN", "SANDHILL CRANE",
            "SATYR TRAGOPAN", "SCARLET IBIS", "SCARLET MACAW", "SCARLET TANAGER", "SHOEBILL", "SHORT BILLED DOWITCHER",
            "SMITHS LONGSPUR", "SNOWY EGRET", "SNOWY OWL", "SORA", "SPANGLED COTINGA", "SPLENDID WREN", "SPOON BILED SANDPIPER",
            "SPOONBILL", "SRI LANKA BLUE MAGPIE", "STEAMER DUCK", "STORK BILLED KINGFISHER", "STRAWBERRY FINCH",
            "STRIPPED MANAKIN", "STRIPPED SWALLOW", "SUPERB STARLING", "SWINHOES PHEASANT", "TAIWAN MAGPIE", "TAKAHE",
            "TASMANIAN HEN", "TEAL DUCK", "TIT MOUSE", "TOUCHAN", "TOWNSENDS WARBLER", "TREE SWALLOW", "TRUMPTER SWAN",
            "TURKEY VULTURE", "TURQUOISE MOTMOT", "UMBRELLA BIRD", "VARIED THRUSH", "VENEZUELIAN TROUPIAL", "VERMILION FLYCATHER",
            "VICTORIA CROWNED PIGEON", "VIOLET GREEN SWALLOW", "VULTURINE GUINEAFOWL", "WALL CREAPER", "WATTLED CURASSOW",
            "WHIMBREL", "WHITE BROWED CRAKE", "WHITE CHEEKED TURACO", "WHITE NECKED RAVEN", "WHITE TAILED TROPIC",
            "WHITE THROATED BEE EATER", "WILD TURKEY", "WILSONS BIRD OF PARADISE", "WOOD DUCK", "YELLOW BELLIED FLOWERPECKER",
            "YELLOW CACIQUE", "YELLOW HEADED BLACKBIRD"
    };
}
